FROM python:3.13-slim AS base

FROM base AS builder

COPY --from=ghcr.io/astral-sh/uv:0.11.3 /uv /uvx /bin/

WORKDIR /app

ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=python3.13

RUN --mount=type=cache,target=/root/.cache \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-dev --no-install-project

FROM base AS starter

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y curl

WORKDIR /app

COPY --from=builder /app/.venv /app/.venv

ENV PATH="/app/.venv/bin:$PATH"

COPY ../../../Downloads /app

RUN chown -R 1000:1000 /app

EXPOSE 8000

USER 1000

CMD ["gunicorn", "main:app", "-c", "gunicorn_config.py"]