import { Nation, NationDetails, Comment } from './nations';

export const MOCK_NATIONS: Nation[] = [
  {
    id: 'tatar',
    name: 'Татары',
    slug: 'tatar',
    population: 5310649,
    image_url: '/tatarstan-map.png',
    status: 'published',
  },
  {
    id: 'russian',
    name: 'Русские',
    slug: 'russian',
    population: 111016896,
    image_url: '/tatarstan-map.png',
    status: 'published',
  },
  {
    id: 'bashkir',
    name: 'Башкиры',
    slug: 'bashkir',
    population: 1584554,
    image_url: '/tatarstan-map.png',
    status: 'published',
  },
  {
    id: 'chuvash',
    name: 'Чуваши',
    slug: 'chuvash',
    population: 1435872,
    image_url: '/tatarstan-map.png',
    status: 'published',
  },
];

export const MOCK_NATION_DETAILS: Record<string, NationDetails> = {
  tatar: {
    id: 'tatar',
    name: 'Татары',
    slug: 'tatar',
    population: 5310649,
    image_url: '/tatarstan-map.png',
    status: 'published',
    info: {
      nation_id: 'tatar',
      origin: 'Тюркское происхождение, ведут историю от Волжской Булгарии.',
      self_name: 'Татарлар',
      language: 'Татарский (кыпчакская группа)',
      religion: 'Ислам суннитского толка',
      facts: 'Второй по численности народ в РФ. Центр культуры — Казань.',
      status: 'published',
    },
    settlement_zones: [
      {
        id: 'z1',
        nation_id: 'tatar',
        region_name: 'Республика Татарстан',
        polygon_data: { regionId: 'tatar_zone' },
        color: '#2e7d32',
        status: 'published',
      },
    ],
    costumes: [],
    games: [
      { id: 'g1', nation_id: 'chuvash', title: 'Угадай блюдо' },
      { id: 'g2', nation_id: 'chuvash', title: 'Угадай праздник' },
      { id: 'g3', nation_id: 'chuvash', title: 'Угадай орнамент' },
    ],
    comments_count: 1,
  },
  russian: {
    id: 'russian',
    name: 'Русские',
    slug: 'russian',
    population: 111016896,
    image_url: '/tatarstan-map.png',
    status: 'published',
    info: {
      nation_id: 'russian',
      origin: 'Восточнославянские племена.',
      self_name: 'Русские',
      language: 'Русский (славянская группа)',
      religion: 'Православие',
      facts: 'Самый многочисленный народ страны.',
      status: 'published',
    },
    settlement_zones: [
      {
        id: 'z2',
        nation_id: 'russian',
        region_name: 'Поволжье и Центр',
        polygon_data: { regionId: 'east_zone' },
        color: '#1565c0',
        status: 'published',
      },
    ],
    costumes: [],
    games: [
      { id: 'g4', nation_id: 'chuvash', title: 'Угадай блюдо' },
      { id: 'g5', nation_id: 'chuvash', title: 'Угадай праздник' },
      { id: 'g6', nation_id: 'chuvash', title: 'Угадай орнамент' },
    ],
    comments_count: 0,
  },
  bashkir: {
    id: 'bashkir',
    name: 'Башкиры',
    slug: 'bashkir',
    population: 1584554,
    image_url: '/tatarstan-map.png',
    status: 'published',
    info: {
      nation_id: 'bashkir',
      origin: 'Тюркский народ, коренное население Южного Урала.',
      self_name: 'Башҡорттар',
      language: 'Башкирский язык',
      religion: 'Ислам суннитского толка',
      facts: 'Славятся своим бортевым медом и искусством игры на курае.',
      status: 'published',
    },
    settlement_zones: [
      {
        id: 'z3',
        nation_id: 'bashkir',
        region_name: 'Приуралье',
        polygon_data: { regionId: 'east_zone' },
        color: '#d87d2d',
        status: 'published',
      },
    ],
    costumes: [],
    games: [
      { id: 'g7', nation_id: 'chuvash', title: 'Угадай блюдо' },
      { id: 'g8', nation_id: 'chuvash', title: 'Угадай праздник' },
      { id: 'g9', nation_id: 'chuvash', title: 'Угадай орнамент' },
    ],
    comments_count: 0,
  },
  chuvash: {
    id: 'chuvash',
    name: 'Чуваши',
    slug: 'chuvash',
    population: 1435872,
    image_url: '/tatarstan-map.png',
    status: 'published',
    info: {
      nation_id: 'chuvash',
      origin: 'Потомки волжских булгар.',
      self_name: 'Чăвашсем',
      language: 'Чувашский язык',
      religion: 'Православие',
      facts: 'Край ста тысяч вышивок.',
      status: 'published',
    },
    settlement_zones: [
      {
        id: 'z4',
        nation_id: 'chuvash',
        region_name: 'Предволжье',
        polygon_data: { regionId: 'tatar_zone' },
        color: '#c62828',
        status: 'published',
      },
    ],
    costumes: [],
    games: [
      { id: 'g10', nation_id: 'chuvash', title: 'Угадай блюдо' },
      { id: 'g11', nation_id: 'chuvash', title: 'Угадай праздник' },
      { id: 'g12', nation_id: 'chuvash', title: 'Угадай орнамент' },
    ],
    comments_count: 0,
  },
};

export const MOCK_COMMENTS: Record<string, Comment[]> = {
  tatar: [
    {
      id: 'c1',
      nation_id: 'tatar',
      user_id: 'u1',
      text: 'Классно!',
      created_at: new Date().toISOString(),
      status: 'approved',
    },
  ],
  russian: [],
  bashkir: [],
  chuvash: [],
};
